name: settlers-remake
title: setters-remake
version: 0.0.1

architectures:
  - build-on: amd64

summary: Settlers III clone for Linux, Mac and Windows

description: |
  Play the classic Settlers III game on modern computers.
  Original game files required for graphics and sound.
  
  This is an installer that easily lets you setup the real game
  and allows switching game releases. Especially useful since
  settlers-remake is still alpha and changes often.
  
  Read more at https://github.com/HiranChaudhuri/settlers-installer/blob/main/README.md

icon: app/src/main/resources/images/siedler3-helme-logo-120.png

contact: https://discord.gg/2hVV4u6
issues: https://github.com/HiranChaudhuri/settlers-installer/issues
source-code: https://github.com/HiranChaudhuri/settlers-installer.git

base: core20
confinement: strict

apps:
  settlers-remake:
    extensions:
      - gnome-3-38
    command: opt/settlersremake/bin/SettlersRemake
    plugs:
      - home
      - network
      - opengl
      - optical-drive

parts:
  settlers-installer:
    plugin: dump
    source: https://github.com/HiranChaudhuri/settlers-installer/releases/download/nightly/settlersremake_1.0-1_amd64.deb
    source-type: deb
