/*
 */
package settlers.installer.ui;

import java.awt.Dimension;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author hiran
 */
public class BugReport extends javax.swing.JPanel {
    
    private Image image;

    /**
     * Creates new form BugReport
     */
    public BugReport() {
        initComponents();
    }

    public Image getImage() {
        return image;
    }
    
    private Dimension scaledSize(Dimension src, Dimension target) {
        double ratio = Math.min(target.getWidth()/src.getWidth(), target.getHeight()/src.getHeight());
        Dimension result = new Dimension();
        result.setSize(src.getWidth()*ratio, src.getHeight()*ratio);
        return result;
    }

    public void setImage(Image image) {
        this.image = image;
        Dimension newSize = scaledSize(new Dimension(image.getWidth(null), image.getHeight(null)), new Dimension(600, 400));
        lbImage.setIcon(new ImageIcon(image.getScaledInstance((int)newSize.getWidth(), (int)newSize.getHeight(), Image.SCALE_AREA_AVERAGING)));
    }
    
    public void setLogfile(String logfilepath) {
        txtLogfile.setText(logfilepath);
    }
    
    public void setReplayFile(String replayfilepath) {
        txtReplay.setText(replayfilepath);
    }

    public void setTitle(String title) {
        txtTitle.setText(title);
    }
    
    public String getTitle() {
        return txtTitle.getText();
    }
    
    public void setDescription(String description) {
        txtDescription.setText(description);
    }
    
    public String getDescription() {
        return txtDescription.getText();
    }
    
    public void setAttachLogfile(boolean attachLogfile) {
        cbLogfile.setSelected(attachLogfile);
    }
    
    public boolean isAttachLogfile() {
        return cbLogfile.isSelected();
    }
    
    public void setAttachReplayfile(boolean attachReplayfile) {
        cbReplayFile.setSelected(attachReplayfile);
    }
    
    public boolean isAttachReplayfile() {
        return cbReplayFile.isSelected();
    }
    
    public void setAttachScreenshot(boolean attachScreenshot) {
        cbScreenshot.setSelected(attachScreenshot);
    }
    
    public boolean isAttachScreenshot() {
        return cbScreenshot.isSelected();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        cbLogfile = new javax.swing.JCheckBox();
        cbReplayFile = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTitle = new javax.swing.JTextField();
        cbScreenshot = new javax.swing.JCheckBox();
        lbImage = new javax.swing.JLabel();
        txtLogfile = new javax.swing.JTextField();
        txtReplay = new javax.swing.JTextField();

        jLabel2.setText("Description");

        txtDescription.setColumns(20);
        txtDescription.setRows(5);
        jScrollPane1.setViewportView(txtDescription);

        cbLogfile.setText("Log File");

        cbReplayFile.setText("Replay File");

        jLabel3.setText("Attachements");

        jLabel4.setText("Issue Title");

        cbScreenshot.setText("Screenshot");

        txtLogfile.setEditable(false);
        txtLogfile.setBorder(null);

        txtReplay.setEditable(false);
        txtReplay.setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                            .addComponent(txtTitle)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbScreenshot)
                            .addComponent(cbReplayFile)
                            .addComponent(cbLogfile))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtLogfile)
                            .addComponent(txtReplay))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbLogfile)
                    .addComponent(jLabel3)
                    .addComponent(txtLogfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbReplayFile)
                    .addComponent(txtReplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbScreenshot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbLogfile;
    private javax.swing.JCheckBox cbReplayFile;
    private javax.swing.JCheckBox cbScreenshot;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbImage;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextField txtLogfile;
    private javax.swing.JTextField txtReplay;
    private javax.swing.JTextField txtTitle;
    // End of variables declaration//GEN-END:variables
}
