/*
 */
package settlers.installer;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 *
 * @author hiran
 */
public class App extends javax.swing.JFrame {
    private static final Logger log = LogManager.getLogger(App.class);

    /**
     * Creates new form App
     */
    public App() {
        initComponents();
        
        Timer timer = new Timer(1500, new ActionListener() {
            
            private int x = 0;
            
            @Override
            public void actionPerformed(ActionEvent ae) {
                x = (x + 1) % 4;
                log.warn(String.format("x = %d", x));
                
                lbDataFound.setVisible( (x & 1) == 0);
                lbGameFound.setVisible( (x & 2) == 0);
                lbDataMissing.setVisible( (x & 1) != 0);
                lbGameMissing.setVisible( (x & 2) != 0);
            }
        });
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        lbGameFound = new javax.swing.JLabel();
        lbGameMissing = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        lbDataFound = new javax.swing.JLabel();
        lbDataMissing = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Settlers-Installer");
        getContentPane().setLayout(new java.awt.GridLayout(2, 1));

        jLayeredPane1.setLayout(new javax.swing.BoxLayout(jLayeredPane1, javax.swing.BoxLayout.LINE_AXIS));

        lbGameFound.setText("Game Found");
        jLayeredPane1.add(lbGameFound);

        lbGameMissing.setText("Game Missing");
        jLayeredPane1.add(lbGameMissing);

        getContentPane().add(jLayeredPane1);

        jLayeredPane2.setLayout(new javax.swing.BoxLayout(jLayeredPane2, javax.swing.BoxLayout.LINE_AXIS));

        lbDataFound.setText("Data Found");
        jLayeredPane2.add(lbDataFound);

        lbDataMissing.setText("Data Missing");
        jLayeredPane2.add(lbDataMissing);

        getContentPane().add(jLayeredPane2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLabel lbDataFound;
    private javax.swing.JLabel lbDataMissing;
    private javax.swing.JLabel lbGameFound;
    private javax.swing.JLabel lbGameMissing;
    // End of variables declaration//GEN-END:variables
}
