# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # require minimum Vagrant version
  Vagrant.require_version ">= 2.2.18"

  config.vm.define :ubuntu do |ubuntu|
    ubuntu.vm.boot_timeout = 120
    ubuntu.vm.box = "ubuntu/focal64"
    ubuntu.vm.hostname = "Settlers-Ubuntu"

    # per default the disk is 40 GB - we need a fraction, but Vagrant does not support shrinking the disk
    #config.vm.disk :disk, size: "20GB", primary: true

    ubuntu.vm.provider "virtualbox" do |uvb|
      # Display the VirtualBox GUI when booting the machine
      uvb.gui = true
      uvb.name = "Settlers-Ubuntu"

      # Customize the amount of memory on the VM:
      uvb.memory = "4096"

      # inspired by https://stackoverflow.com/questions/21986511/how-to-add-storage-settings-to-vagrant-file
      uvb.customize ["storageattach", :id, "--storagectl", "IDE", "--port", "0", "--device", "0", "--type", "dvddrive", "--medium", "emptydrive"]
      uvb.customize ["modifyvm", :id, "--boot1", "disk", "--boot2", "dvd", "--boot3", "none", "--boot4", "none"]
      uvb.customize ["modifyvm", :id, "--clipboard-mode", "bidirectional"]
      #uvb.customize ["modifyvm", :id, "--iconfile", "Appliance_Logo.png"]
      #uvb.customize ["modifyvm", :id, "--graphicscontroller", "vboxsvga"] -- it seems vmsvga is the recommended adapter
      uvb.customize ["modifyvm", :id, "--graphicscontroller", "vmsvga"]
    end

    ubuntu.vm.provision :ansible do |ansible|
      ansible.playbook = "playbook-ubuntu.yml"
      ansible.verbose = "vv"
    end
  end

#  config.vm.define :arch do |arch|
#    arch.vm.boot_timeout = 120
#    arch.vm.box = "archlinux/archlinux"
#    arch.vm.hostname = "Settlers-Arch"
#    arch.vm.provider "virtualbox" do |avb|
#      avb.gui = true
#      avb.name = "Settlers-Arch"
#      avb.memory = "4096"
#
#      avb.customize ["storageattach", :id, "--storagectl", "IDE Controller", "--port", "0", "--device", "1", "--type", "dvddrive", "--medium", "emptydrive"]
#      avb.customize ["modifyvm", :id, "--boot1", "disk", "--boot2", "dvd", "--boot3", "none", "--boot4", "none"]
#      avb.customize ["modifyvm", :id, "--clipboard-mode", "bidirectional"]
#      #avb.customize ["modifyvm", :id, "--iconfile", "Appliance_Logo.png"]
#      #avb.customize ["modifyvm", :id, "--graphicscontroller", "vboxsvga"] -- it seems vmsvga is the recommended adapter
#      avb.customize ["modifyvm", :id, "--graphicscontroller", "vmsvga"]
#    end
#
#    arch.vm.provision :ansible do |ansible|
#      ansible.playbook = "playbook-arch.yml"
#      ansible.verbose = "vv"
#    end
#  end

end
