name: Nightly

on:
  push:
  workflow_dispatch:

jobs:
  build-Linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with gradle
      run: |
        printenv | sort
        ./gradlew --info jpackage
        ls -l app/build

    - uses: actions/upload-artifact@v2
      with:
        name: SettlersRemake.deb
        path: app/build/SettlersRemake*.deb

  build-Windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    - uses: gradle/gradle-build-action@v2
      with:
        arguments: --info jpackage

  build-MacOS:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with gradle
      run: |
        printenv | sort
        ./gradlew --info jpackage
        ls -l app/build
