name: Nightly

on:
  push:
  workflow_dispatch:

jobs:
  build-Linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build with gradle
      run: |
        printenv | sort
        ./gradlew jpackage
        ls -l app/build

    - uses: actions/upload-artifact@v2
      with:
        name: SettlersRemake.deb
        path: app/build/SettlersRemake*.deb

