name: Nightly

on:
  push:
  workflow_dispatch:

jobs:
  build-Linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with gradle
      run: |
        #!/bin/bash -x
        printenv | sort
        ./gradlew --info build
        
    - name: Create app-image using JPackage
      run: |
        #!/bin/bash -x
        set -x
        echo --Preparing directories
        mkdir -p app/build/jpackage_input || exit 1
        mkdir -p app/build/resources/jpackage || exit 1
        cp app/src/jpackage/resources/* app/build/resources/jpackage
        APPVERSION=`basename app/build/distributions/*.zip .zip`
        VERSION=`echo $APPVERSION | cut -d- -f2-`
        pushd .; cd app/build/jpackage_input; unzip ../distributions/*.zip; popd
        echo --Checking input directories...
        find app/build/jpackage_input
        find app/build/distributions
        find app/build/resources
        echo --Running jpackage...
        jpackage --verbose --type app-image --dest app/build/app-image -i "app/build/jpackage_input/app-${VERSION}/lib" --main-jar "app-${VERSION}.jar" --main-class settlers.installer.App --name SettlersRemake --app-version "${VERSION}" --description 'Settlers 3 remake - see https://github.com/' --vendor Hiran, --icon "app/build/resources/main/siedler3-helme-logo.png" --resource-dir "app/build/resources/jpackage" --jlink-options "--strip-debug --no-man-pages --no-header-files"
        echo --Checking output directory
        find app/build/app-image
        
    - name: Modify app-image
      run: |
        #!/bin/bash -x
        ./gradlew --info filterResourcesCopy jpackageInterfere
        find app/build/resources

    - name: Build package
      run: |
        #!/bin/bash -x
        echo "-- Checking input directory"
        find app/build/app-image
        echo "-- Run jpackage phase 2"
        jpackage --verbose --app-image app/build/app-image/SettlersRemake --name SettlersRemake --dest app/build/distributions --resource-dir app/build/resources/jpackage
        echo "-- Checking output directory"
        find app/build/distributions

    - uses: actions/upload-artifact@v2
      with:
        name: SettlersRemake-Linux
        path: app/build/distributions/*

  build-Windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with gradle
      run: |
        # PowerShell
        ./gradlew --info build

    - name: Create app-image using JPackage
      run: |
        # PowerShell
        Set-PSDebug -Trace 1
        echo --Preparing directories
        mkdir -p app/build/jpackage_input || exit 1
        mkdir -p app/build/resources/jpackage || exit 1
        copy app/src/jpackage/resources/* app/build/resources/jpackage
        $APPVERSION = dir app/build/distributions/*.zip | select -ExpandProperty BaseName
        $APPVERSION -match "^[^-]*-([^-]+)(-[^-]+)?"
        echo APPVERSION=$APPVERSION
        $VERSION=$Matches.1
        echo VERSION=$VERSION
        Push-Location app/build/jpackage_input
        unzip ../distributions/*.zip
        Pop-Location
        echo --Checking directories...
        Get-ChildItem -Recurse app/build/jpackage_input
        Get-ChildItem -Recurse app/build/distributions
        Get-ChildItem -Recurse app/build/resources
        echo "--Running jpackage..."
        jpackage --verbose --type app-image --dest app/build/app-image -i "app/build/jpackage_input/${APPVERSION}/lib" --main-jar "${APPVERSION}.jar" --main-class settlers.installer.App --name SettlersRemake --app-version "${VERSION}" --description 'Settlers 3 remake - see https://github.com/' --vendor Hiran, --icon "app/build/resources/main/siedler3-helme-logo.png" --resource-dir "app/build/resources/jpackage" --jlink-options "--strip-debug --no-man-pages --no-header-files"
        echo "--Checking output directory"
        Get-ChildItem -Recurse app/build/app-image

    - name: Modify app-image
      run: |
        # PowerShell
        ./gradlew --info filterResourcesCopy jpackageInterfere
        echo "--Checking output directory"
        Get-ChildItem -Recurse app/build/resources
        Get-ChildItem -Recurse app/build/app-image

    - name: Build package
      run: |
        # PowerShell
        jpackage --verbose --app-image app/build/app-image/SettlersRemake --name SettlersRemake --dest app/build/distributions --resource-dir app/build/resources/jpackage
        Get-ChildItem -Recurse app/build/distributions

    - uses: actions/upload-artifact@v2
      with:
        name: SettlersRemake-Windows
        path: app/build/distributions/*

  build-MacOS:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with gradle
      run: |
        #!/bin/bash -x
        printenv | sort
        ./gradlew --info build
        
    - name: Create app-image using JPackage
      run: |
        #!/bin/bash -x
        set -x
        echo --Preparing directories
        mkdir -p app/build/jpackage_input || exit 1
        mkdir -p app/build/resources/jpackage || exit 1
        cp app/src/jpackage/resources/* app/build/resources/jpackage
        APPVERSION=`basename app/build/distributions/*.zip .zip`
        VERSION=`echo $APPVERSION | cut -d- -f2-`
        MACVERSION=`echo $APPVERSION | cut -d- -f2`
        MACVERSION=${MACVERSION#0.}
        pushd .;cd app/build/jpackage_input;unzip ../distributions/*.zip;popd
        echo --Checking directories...
        find app/build/jpackage_input
        find app/build/distributions
        find app/build/resources
        echo --Running jpackage...
        jpackage --verbose --type app-image --dest app/build/app-image -i "app/build/jpackage_input/app-${VERSION}/lib" --main-jar "app-${VERSION}.jar" --main-class settlers.installer.App --name SettlersRemake --app-version "${MACVERSION}" --description 'Settlers 3 remake - see https://github.com/' --vendor Hiran, --icon "app/build/resources/main/siedler3-helme-logo.png" --resource-dir "app/build/resources/jpackage" --jlink-options "--strip-debug --no-man-pages --no-header-files"
        echo --Checking output directory
        find app/build/app-image
        
    - name: Modify app-image
      run: |
        #!/bin/bash -x
        ./gradlew --info filterResourcesCopy
        find app/build/resources

    - name: Build package
      run: |
        #!/bin/bash -x
        jpackage --verbose --app-image app/build/app-image/SettlersRemake.app --name SettlersRemake --dest app/build/distributions --resource-dir app/build/resources/jpackage
        find app/build/distributions

    - uses: actions/upload-artifact@v2
      with:
        name: SettlersRemake-MacOS
        path: app/build/distributions/*

  release:
    if: ${{ always() }}
    needs:
      - build-Windows
      - build-Linux
      - build-MacOS
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v2

      - name: check environment after download
        run: find .

      - name: Publish Release
        id: publish_release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "nightly"
          prerelease: false
          title: "Settlers-Installer Nightly"
          files: |
            SettlersRemake-Linux/*.deb
            SettlersRemake-Windows/*
            SettlersRemake-MacOS/*.dmg
