name: Nightly

on:
  push:
  workflow_dispatch:

jobs:
  build-Linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with gradle
      run: |
        #!/bin/bash -x
        printenv | sort
        ./gradlew --info build
        
    - name: Package using JPackage
      run: |
        #!/bin/bash -x
        mkdir -p app/build/jpackage-input || exit 1
        mkdir -p app/build/resources/jpackage || exit 1
        cp app/src/main/resources/jpackage/* app/build/resources/jpackage
        APPVERSION=`basename app/build/distributions/*.zip`
        VERSION=`echo $APPVERSION | cut -d- -f2`
        pushd .;cd app/build/jpackage-input;unzip ../distributions/*.zip;popd
        find app/build/distributions
        jpackage --type app-image --dest build/app-image -i "build/jpackage_input/app-${VERSION}/lib" --main-jar "app-${VERSION}.jar" --main-class settlers.installer.App --name SettlersRemake --app-version "${VERSION}" --description 'Settlers 3 remake - see https://github.com/' --vendor Hiran, --icon "build/resources/main/siedler3-helme-logo.png" --resource-dir "build/resources/jpackage"
        find app/build/app-image

    - uses: actions/upload-artifact@v2
      with:
        name: SettlersRemake
        path: app/build/distributions/*

#  build-Windows:
#    runs-on: windows-latest
#    
#    steps:
#    - uses: actions/checkout@v2
#    - name: Setup JDK 17
#      uses: actions/setup-java@v2
#      with:
#        java-version: '17'
#        distribution: 'temurin'
#    - uses: gradle/gradle-build-action@v2
#      with:
#        arguments: --info jpackage

#  build-MacOS:
#    runs-on: macos-latest
#
#    steps:
#    - uses: actions/checkout@v2
#    - name: Setup JDK 17
#      uses: actions/setup-java@v2
#      with:
#        java-version: '17'
#        distribution: 'temurin'
#
#    - name: Build with gradle
#      run: |
#        printenv | sort
#        ./gradlew --info jpackage
#        ls -l app/build
